-- ============================================================================
-- Proactive Insights Schema Alignment
-- Date: 2026-02-22
--
-- The service code (api/services/proactiveInsights.js) uses a simpler schema
-- than the original pattern_learning_tables migration (20260203).
--
-- Original migration had: insight_type, title, description, was_shown, ...
-- Service code uses:      insight (text), urgency, category, delivered, delivered_at
--
-- This migration ensures the correct columns exist regardless of which version
-- of the table was applied. All operations are idempotent.
--
-- Service schema requirements:
--   INSERT: user_id, insight, urgency, category
--   SELECT: id, insight, urgency, category, created_at + filter on delivered=false
--   UPDATE: delivered=true, delivered_at=now()
-- ============================================================================

-- Create the table with the correct schema if it doesn't exist yet.
-- If it already exists (from pattern_learning_tables migration), this is a no-op.
CREATE TABLE IF NOT EXISTS proactive_insights (
  id           UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  insight      TEXT        NOT NULL,
  urgency      VARCHAR(10) NOT NULL DEFAULT 'low'
    CHECK (urgency IN ('low', 'medium', 'high')),
  category     VARCHAR(50),
  delivered    BOOLEAN     NOT NULL DEFAULT false,
  delivered_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add columns that the service requires, in case the table was created from
-- the older pattern_learning_tables migration which used different column names.

-- insight: primary content field (old schema used title + description instead)
ALTER TABLE proactive_insights
  ADD COLUMN IF NOT EXISTS insight TEXT;

-- urgency: priority level (old schema used priority_score numeric instead)
ALTER TABLE proactive_insights
  ADD COLUMN IF NOT EXISTS urgency VARCHAR(10) DEFAULT 'low';

-- category: classification label (old schema used insight_category)
ALTER TABLE proactive_insights
  ADD COLUMN IF NOT EXISTS category VARCHAR(50);

-- delivered: replaces was_shown from old schema
ALTER TABLE proactive_insights
  ADD COLUMN IF NOT EXISTS delivered BOOLEAN NOT NULL DEFAULT false;

-- delivered_at: timestamp when insight was shown in chat
ALTER TABLE proactive_insights
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;

-- Indexes for service access patterns
CREATE INDEX IF NOT EXISTS idx_proactive_insights_user_id
  ON proactive_insights (user_id, created_at DESC);

-- Partial index for undelivered insights (most common query pattern)
CREATE INDEX IF NOT EXISTS idx_proactive_insights_undelivered
  ON proactive_insights (user_id) WHERE delivered = false;

-- Enable RLS (safe to call even if already enabled)
ALTER TABLE proactive_insights ENABLE ROW LEVEL SECURITY;

-- Drop and recreate policies for service access patterns
DROP POLICY IF EXISTS "Users view own proactive_insights"   ON proactive_insights;
DROP POLICY IF EXISTS "Users insert own proactive_insights" ON proactive_insights;
DROP POLICY IF EXISTS "Users update own proactive_insights" ON proactive_insights;
DROP POLICY IF EXISTS "Service role full access proactive_insights" ON proactive_insights;

-- Users can view their own insights
CREATE POLICY "Users view own proactive_insights"
  ON proactive_insights FOR SELECT
  USING ((SELECT auth.uid()) = user_id);

-- Service role has full access (backend generates and marks delivered)
CREATE POLICY "Service role full access proactive_insights"
  ON proactive_insights FOR ALL
  TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE proactive_insights IS
  'Proactive insights generated by twin from pattern analysis. Delivered in chat context.';
COMMENT ON COLUMN proactive_insights.delivered IS
  'True after insight has been included in a twin chat response.';
