import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--background)', color: 'var(--foreground)' }}>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <button
          onClick={() => navigate(-1)}
          className="mb-8 text-sm flex items-center gap-2 transition-opacity hover:opacity-70"
          style={{ color: 'var(--text-secondary)', fontFamily: 'var(--font-body)' }}
        >
          <ArrowLeft className="w-4 h-4" />
          Back
        </button>

        <h1 className="heading-serif text-3xl mb-2">
          Terms of Service
        </h1>
        <p className="text-sm mb-10" style={{ color: 'var(--text-secondary)' }}>
          Last updated: March 7, 2026
        </p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ fontFamily: 'var(--font-body)' }}>
          <section>
            <h2 className="heading-serif text-lg mb-3">1. Acceptance of Terms</h2>
            <p style={{ color: 'var(--foreground)' }}>
              By accessing or using Twin Me ("the Service"), you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">2. Description of Service</h2>
            <p style={{ color: 'var(--foreground)' }}>
              Twin Me is a personality discovery platform that creates a digital twin from patterns in
              your digital life. The Service analyzes data from connected platforms to generate
              personality insights, power an AI twin, and help you understand yourself better.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">3. Account Registration</h2>
            <p style={{ color: 'var(--foreground)' }}>
              To use the Service, you must create an account using Google OAuth. You are responsible
              for maintaining the security of your account and for all activities that occur under
              your account. You must be at least 13 years old to use the Service.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">4. User Data & Platform Connections</h2>
            <p className="mb-3" style={{ color: 'var(--foreground)' }}>
              When you connect third-party platforms (such as Spotify, Google Calendar, YouTube, or
              others), you authorize Twin Me to access the data specified during the OAuth flow. You
              may disconnect any platform at any time through Settings, which revokes our access to
              that platform's data.
            </p>
            <p style={{ color: 'var(--foreground)' }}>
              Your use of connected platforms remains subject to those platforms' own terms of service
              and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">5. Acceptable Use</h2>
            <p className="mb-3" style={{ color: 'var(--foreground)' }}>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2" style={{ color: 'var(--foreground)' }}>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Create accounts on behalf of others without their consent</li>
              <li>Use automated means to access the Service without our permission</li>
              <li>Reverse engineer or attempt to extract the source code of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">6. AI-Generated Content</h2>
            <p style={{ color: 'var(--foreground)' }}>
              The digital twin and personality insights are generated by AI models. While we strive
              for accuracy, AI-generated content may not always be correct or complete. The Service
              is intended for personal discovery and entertainment purposes. You should not rely on
              AI-generated insights for medical, legal, financial, or other professional decisions.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">7. Intellectual Property</h2>
            <p style={{ color: 'var(--foreground)' }}>
              The Service, including its design, features, and underlying technology, is owned by
              Twin Me. You retain ownership of any personal data you provide. By using the Service,
              you grant us a limited license to process your data solely for the purpose of
              providing the Service to you.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">8. Privacy</h2>
            <p style={{ color: 'var(--foreground)' }}>
              Your privacy is important to us. Please review our{" "}
              <a href="/privacy-policy" className="underline hover:opacity-70 transition-opacity">
                Privacy Policy
              </a>{" "}
              to understand how we collect, use, and protect your data.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">9. Account Termination</h2>
            <p style={{ color: 'var(--foreground)' }}>
              You may delete your account at any time through Settings. Upon deletion, all your
              personal data will be permanently and immediately removed. We reserve the right to
              suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">10. Disclaimers</h2>
            <p style={{ color: 'var(--foreground)' }}>
              The Service is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We do not guarantee that the Service will be uninterrupted,
              error-free, or that AI-generated content will be accurate or suitable for any
              particular purpose.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">11. Limitation of Liability</h2>
            <p style={{ color: 'var(--foreground)' }}>
              To the maximum extent permitted by law, Twin Me shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of or
              inability to use the Service.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">12. Changes to Terms</h2>
            <p style={{ color: 'var(--foreground)' }}>
              We may update these Terms of Service from time to time. We will notify users of
              significant changes through the application. Continued use of the Service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="heading-serif text-lg mb-3">13. Contact</h2>
            <p style={{ color: 'var(--foreground)' }}>
              If you have questions about these Terms of Service, please contact us through the
              Settings page in the application, or email us at support@twinme.ai.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
