import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useLenis } from "../hooks/useLenis";
import { PageHead } from "@/components/register";
import "../styles/legal.css";

/**
 * /terms, in the register (src/styles/legal.css): the kit's column and title,
 * each numbered section on the section heading. The terms themselves are
 * unchanged.
 */
const TermsOfService = () => {
  const navigate = useNavigate();
  useLenis();

  return (
    // Standalone page (no SidebarLayout), so it must provide the
    // #main-content landmark the App.tsx skip-link targets (audit-2026-07-03)
    <main id="main-content" className="lg">
      <div className="rg-page">
        <button
          type="button"
          aria-label="Go back to previous page"
          onClick={() => navigate(-1)}
          className="n-btn n-btn--ghost lg-back"
        >
          <ArrowLeft className="w-4 h-4" aria-hidden="true" />
          Back
        </button>

        <PageHead title="Terms of service" line="Last updated: March 7, 2026" />

        <div className="lg-doc">
          <section>
            <h2>1. Acceptance of terms</h2>
            <p>
              By accessing or using Twin Me ("the Service"), you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2>2. Description of service</h2>
            <p>
              Twin Me is a personality discovery platform that creates a digital twin from patterns in
              your digital life. The Service analyzes data from connected platforms to generate
              personality insights, power an AI twin, and help you understand yourself better.
            </p>
          </section>

          <section>
            <h2>3. Account registration</h2>
            <p>
              To use the Service, you must create an account using Google OAuth. You are responsible
              for maintaining the security of your account and for all activities that occur under
              your account. You must be at least 13 years old to use the Service.
            </p>
          </section>

          <section>
            <h2>4. User data and platform connections</h2>
            <p>
              When you connect third-party platforms (such as Spotify, Google Calendar, YouTube, or
              others), you authorize Twin Me to access the data specified during the OAuth flow. You
              may disconnect any platform at any time through Settings, which revokes our access to
              that platform's data.
            </p>
            <p>
              Your use of connected platforms remains subject to those platforms' own terms of service
              and privacy policies.
            </p>
          </section>

          <section>
            <h2>5. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Create accounts on behalf of others without their consent</li>
              <li>Use automated means to access the Service without our permission</li>
              <li>Reverse engineer or attempt to extract the source code of the Service</li>
            </ul>
          </section>

          <section>
            <h2>6. AI-generated content</h2>
            <p>
              The digital twin and personality insights are generated by AI models. While we strive
              for accuracy, AI-generated content may not always be correct or complete. The Service
              is intended for personal discovery and entertainment purposes. You should not rely on
              AI-generated insights for medical, legal, financial, or other professional decisions.
            </p>
          </section>

          <section>
            <h2>7. Intellectual property</h2>
            <p>
              The Service, including its design, features, and underlying technology, is owned by
              Twin Me. You retain ownership of any personal data you provide. By using the Service,
              you grant us a limited license to process your data solely for the purpose of
              providing the Service to you.
            </p>
          </section>

          <section>
            <h2>8. Privacy</h2>
            <p>
              Your privacy is important to us. Please review our{" "}
              <a href="/privacy-policy">Privacy Policy</a>{" "}
              to understand how we collect, use, and protect your data.
            </p>
          </section>

          <section>
            <h2>9. Account termination</h2>
            <p>
              You may delete your account at any time through Settings. Upon deletion, all your
              personal data will be permanently and immediately removed. We reserve the right to
              suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2>10. Disclaimers</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind,
              either express or implied. We do not guarantee that the Service will be uninterrupted,
              error-free, or that AI-generated content will be accurate or suitable for any
              particular purpose.
            </p>
          </section>

          <section>
            <h2>11. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Twin Me shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of or
              inability to use the Service.
            </p>
          </section>

          <section>
            <h2>12. Changes to terms</h2>
            <p>
              We may update these Terms of Service from time to time. We will notify users of
              significant changes through the application. Continued use of the Service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2>13. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please contact us through the
              Settings page in the application, or email us at{" "}
              <a href="mailto:support@twinme.me">support@twinme.me</a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
};

export default TermsOfService;
