-- Codebase-wide RLS sweep
--
-- Context: the broken `auth.uid() = user_id` pattern was discovered during the
-- /goals and /wiki audits. Every public.* table's user_id FK points at
-- public.users.id, not auth.users.id. public.users.id is generated by the
-- application (separate UUID from auth.users.id), so auth.uid() never equals
-- user_id at runtime -- every such policy evaluates false for every row.
--
-- The backend talks to Postgres through the service_role key, which has
-- BYPASSRLS, so the broken policies were a hygiene problem rather than a
-- runtime block. This migration:
--   1. Drops every policy whose qual or with_check matches the broken
--      auth.uid()/user_id ownership pattern across all public.* tables.
--   2. Ensures every table that just lost its last non-service_role policy
--      retains an explicit service_role full-access policy as defense in
--      depth (in case BYPASSRLS is ever revoked).
--
-- Scope: only policies referencing BOTH `auth.uid()` AND `user_id`. Admin /
-- subscription / id-based policies (e.g. `id = auth.uid()` on a few tables)
-- are deliberately untouched and tracked separately.

DO $$
DECLARE
  pol RECORD;
  drop_count INT := 0;
BEGIN
  FOR pol IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND (
        qual       ILIKE '%auth.uid()%user_id%'
        OR qual       ILIKE '%user_id%auth.uid()%'
        OR with_check ILIKE '%auth.uid()%user_id%'
        OR with_check ILIKE '%user_id%auth.uid()%'
      )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I',
                   pol.policyname, pol.schemaname, pol.tablename);
    drop_count := drop_count + 1;
  END LOOP;
  RAISE NOTICE 'Dropped % broken auth.uid()=user_id policies', drop_count;
END $$;


DO $$
DECLARE
  t RECORD;
  create_count INT := 0;
BEGIN
  FOR t IN
    SELECT c.relname AS tablename
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND c.relrowsecurity = true
      AND NOT EXISTS (
        SELECT 1 FROM pg_policies p
        WHERE p.schemaname = 'public'
          AND p.tablename = c.relname
          AND 'service_role' = ANY(p.roles)
      )
  LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
      'service_role_full_access', t.tablename
    );
    create_count := create_count + 1;
  END LOOP;
  RAISE NOTICE 'Created % service_role policies', create_count;
END $$;
