/**
 * Demo Goals Data
 * Twin-driven goals for demo mode
 */

import type { Goal, GoalSummary } from '../api/goalsAPI';

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();
const daysAhead = (d: number) => new Date(now + d * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_ACTIVE_GOALS: Goal[] = [
  {
    id: 'demo-goal-active-1',
    title: '30 min daily focus music',
    description: 'Listen to at least 30 minutes of focused/instrumental music each workday to support deep work sessions.',
    category: 'focus',
    source_platform: 'spotify',
    source_observation: 'Listening patterns show music correlates with 40% longer focus blocks.',
    metric_type: 'minutes_listened',
    target_value: 30,
    target_operator: '>=',
    target_unit: 'minutes',
    measurement_window: 'daily',
    status: 'active',
    start_date: daysAgo(18),
    end_date: daysAhead(12),
    duration_days: 30,
    current_streak: 6,
    best_streak: 6,
    total_days_tracked: 18,
    total_days_met: 15,
    last_progress_check: daysAgo(0),
    last_mentioned_at: daysAgo(1),
    celebration_delivered: false,
    metadata: {},
    created_at: daysAgo(18),
    updated_at: daysAgo(0),
  },
  {
    id: 'demo-goal-active-2',
    title: '2h daily deep work block',
    description: 'Protect at least 2 uninterrupted hours for deep work in your calendar every weekday.',
    category: 'focus',
    source_platform: 'google_calendar',
    source_observation: 'Calendar data shows Tuesday/Wednesday deep work blocks are most productive.',
    metric_type: 'hours_blocked',
    target_value: 2,
    target_operator: '>=',
    target_unit: 'hours',
    measurement_window: 'daily',
    status: 'active',
    start_date: daysAgo(10),
    end_date: daysAhead(20),
    duration_days: 30,
    current_streak: 4,
    best_streak: 7,
    total_days_tracked: 10,
    total_days_met: 8,
    last_progress_check: daysAgo(0),
    last_mentioned_at: daysAgo(2),
    celebration_delivered: false,
    metadata: {},
    created_at: daysAgo(10),
    updated_at: daysAgo(0),
  },
];

export const DEMO_SUGGESTED_GOALS: Goal[] = [
  {
    id: 'demo-goal-suggested-1',
    title: 'Discover one new artist weekly',
    description: 'Your listening diversity has been decreasing. Try exploring one new artist from Spotify recommendations each week.',
    category: 'balance',
    source_platform: 'spotify',
    source_observation: 'Top 10 artists account for 78% of your listening — unusually concentrated.',
    metric_type: 'new_artists_discovered',
    target_value: 1,
    target_operator: '>=',
    target_unit: 'artists',
    measurement_window: 'weekly',
    status: 'suggested',
    start_date: null,
    end_date: null,
    duration_days: 28,
    current_streak: 0,
    best_streak: 0,
    total_days_tracked: 0,
    total_days_met: 0,
    last_progress_check: null,
    last_mentioned_at: null,
    celebration_delivered: false,
    metadata: {},
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-goal-suggested-2',
    title: 'Reduce late-evening meetings',
    description: 'You have 3+ meetings after 6pm this week. Protecting your evenings could improve your recovery scores.',
    category: 'schedule',
    source_platform: 'google_calendar',
    source_observation: '6 late-evening meetings (after 6pm) in the last two weeks.',
    metric_type: 'late_meetings_count',
    target_value: 1,
    target_operator: '<=',
    target_unit: 'meetings per week',
    measurement_window: 'weekly',
    status: 'suggested',
    start_date: null,
    end_date: null,
    duration_days: 21,
    current_streak: 0,
    best_streak: 0,
    total_days_tracked: 0,
    total_days_met: 0,
    last_progress_check: null,
    last_mentioned_at: null,
    celebration_delivered: false,
    metadata: {},
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-goal-suggested-3',
    title: 'Watch 3 learning videos per week',
    description: 'You have 12 YouTube subscriptions in the tech/learning category. Consistent viewing could accelerate your skill development.',
    category: 'focus',
    source_platform: 'youtube',
    source_observation: 'Subscribed to 12 educational channels but average only 1.2 videos watched per week.',
    metric_type: 'educational_videos_watched',
    target_value: 3,
    target_operator: '>=',
    target_unit: 'videos',
    measurement_window: 'weekly',
    status: 'suggested',
    start_date: null,
    end_date: null,
    duration_days: 28,
    current_streak: 0,
    best_streak: 0,
    total_days_tracked: 0,
    total_days_met: 0,
    last_progress_check: null,
    last_mentioned_at: null,
    celebration_delivered: false,
    metadata: {},
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
];

export const DEMO_COMPLETED_GOALS: Goal[] = [
  {
    id: 'demo-goal-completed-1',
    title: 'Build a 7-day listening streak',
    description: 'Listen to music every day for 7 consecutive days to build the habit.',
    category: 'focus',
    source_platform: 'spotify',
    source_observation: null,
    metric_type: 'listening_streak',
    target_value: 7,
    target_operator: '>=',
    target_unit: 'days',
    measurement_window: 'cumulative',
    status: 'completed',
    start_date: daysAgo(21),
    end_date: daysAgo(14),
    duration_days: 7,
    current_streak: 0,
    best_streak: 7,
    total_days_tracked: 7,
    total_days_met: 7,
    last_progress_check: daysAgo(14),
    last_mentioned_at: daysAgo(14),
    celebration_delivered: true,
    metadata: {},
    created_at: daysAgo(21),
    updated_at: daysAgo(14),
  },
];

export const DEMO_GOAL_SUMMARY: GoalSummary = {
  active: DEMO_ACTIVE_GOALS.length,
  suggested: DEMO_SUGGESTED_GOALS.length,
  completed: DEMO_COMPLETED_GOALS.length,
  bestStreak: 7,
  categories: ['focus', 'schedule', 'balance'],
};
